services:
  # app:
  #   image: php:latest
  #   container_name: php_start
  #   depends_on:
  #     - db
  #   command: bash -c "cd dbz_api; php -S 0.0.0.0:8080 -t public"


  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbz_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data: